---
- name  : Apache Installation
  hosts : all
  tasks :

    - name  : install Apache2
      yum:
        name: httpd
        state: present

    - name: start Apache2
      systemd:
        name: httpd
        state: started
        enabled: true

    - name: Html File
      copy:
        src: index.html
        dest: /var/www/html/index.html
